; PlatformIO project configuration
; Docs: https://docs.platformio.org/page/projectconf.html

[env:d1_mini]
platform = espressif8266
board = d1_mini            ; Wemos/LOLIN D1 mini. Change to nodemcuv2 for a NodeMCU.
framework = arduino

; Serial monitor / upload
monitor_speed = 115200
upload_speed = 921600
; Decode addresses in stack traces from the monitor:
monitor_filters = esp8266_exception_decoder, default

lib_deps =
	beegee-tokyo/DHT sensor library for ESPx@^1.19   ; DHT11/22 sensor (DHTesp)
	zinggjm/GxEPD2@^1.5.6               ; e-paper driver (incl. GxEPD2_4C 4-color)
	adafruit/Adafruit GFX Library@^1.11.0
